version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile

    ports:
      - 8000:8000

    env_file: .env

    environment:
      - PYTHONDONTWRITEBYTECODE=1

    volumes:
      - ./app:/app
